version: '3.9'
services:
  user-postgres:
    image: postgres:14.2
    expose:
      - "5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-test}
      POSTGRES_DB: "userservice"

  user-service:
    image: userservice
    depends_on:
      - user-postgres
    build:
      context: .
      dockerfile: User-Service/Dockerfile
    ports:
      - "5053:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Staging

networks:
  default:
    name: swsp
